services:
  nginx:
    image: nginx:latest
    container_name: cfssl-nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      # Mount the correct nginx.conf file
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount server certs directory (fullchain.pem & server-key.pem)
      - ../server:/etc/nginx/certs:ro
